Simplon\BlogBundle\Entity\Article:
    properties:
        titre: 
          - NotBlank: { message: "Le titre est obligatoire" }
          - Length: 
              max: 50
              maxMessage: "Le titre ne doit pas dépasser {{ limit }} caractères" 
        
        contenu:
          - NotBlank: { message: "Le contenu est obligatoire" }

Simplon\BlogBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: mail

    properties:
        mail:
          - NotBlank: { message : Email obligatoire }
          - Email:
              message: Email non valide

        password:
          - NotBlank: { message : Il faut un mot de passe }
