renaud_blog_homepage:
    path:     /
    defaults: { _controller: renaudBlogBundle:Blog:index }

renaud_blog_admin_articles:
    path:     /adminArticles
    defaults: { _controller: renaudBlogBundle:Blog:adminArticles}

renaud_blog_add_article:
    path:     /add
    defaults: { _controller: renaudBlogBundle:Blog:add}

renaud_blog_login:
    path:     /login
    defaults: { _controller: renaudBlogBundle:Blog:login}

renaud_blog_register:
    path:     /register
    defaults: { _controller: renaudBlogBundle:Blog:register}

renaud_blog_view_article:
    path:     /view/{id}
    defaults: { _controller: renaudBlogBundle:Blog:view}
    requirements:
        id: \d+