renaud_blog_homepage:
    path:     /
    defaults: { _controller: renaudBlogBundle:Blog:index }

renaud_blog_listeArticles:
    path:     /articles
    defaults: { _controller: renaudBlogBundle:Blog:listeArticles }

renaud_blog_admin_articles:
    path:     /adminArticles
    defaults: { _controller: renaudBlogBundle:Blog:adminArticles }

renaud_blog_add_article:
    path:     /add
    defaults: { _controller: renaudBlogBundle:Blog:add }

renaud_blog_register:
    path:     /register
    defaults: { _controller: renaudBlogBundle:Blog:register }

renaud_blog_view_article:
    path:     /view/{id}
    defaults: { _controller: renaudBlogBundle:Blog:view }
    requirements:
        id: \d+

renaud_blog_remove_article:
    path:   /remove/{id}
    defaults: { _controller: renaudBlogBundle:Blog:remove }
    requirements:
        id: \d+

renaud_blog_update_article:
    path:  /update/{id}
    defaults: { _controller: renaudBlogBundle:Blog:update }
    requirements:
        id: \d+

renaud_blog_publier_article:
    path: /publier/{id}
    defaults: { _controller: renaudBlogBundle:Blog:publier }
    requirements:
        id: \d+

renaud_blog_edit_profile:
    path: /profil/{id}
    defaults: { _controller: renaudBlogBundle:Blog:editProfile }

renaud_blog_login:
    path: /login
    defaults: { _controller: renaudBlogBundle:User:login }

renaud_blog_login_check:
    path: /login_check

renaud_blog_logout:
    path: /logout