renaud\BlogBundle\Entity\Article:
    properties:
        titre: 
          - NotBlank: { message: "Le titre est obligatoire" }
          - Length: 
              max: 50
              maxMessage: "Le titre ne doit pas dépasser {{ limit }} caractères" 
        
        contenu:
          - NotBlank: { message: "Le contenu est obligatoire" }
        
        auteur:
          - NotBlank: { message: "Le nom de l'auteur est obligatoire" }
          - Length:
              max: 30
              maxMessage: "Le nom de l'auteur ne doit pas dépasser {{ limit }} caractères"

renaud\BlogBundle\Entity\User:
    constraints:
        - Symfony\Bridge\Doctrine\Validator\Constraints\UniqueEntity: mail

    properties:
        mail:
          - NotBlank: { message : Email obligatoire }
          - Email:
              message: Email non valide

        nom:
          - NotBlank: { message : Le nom est obligatoire }
          - Length:
              min: 5
              max: 30
              maxMessage: "Le nom ne doit pas dépasser {{ limit }} caractères"
              minMessage: "Le nom doit contenir {{ limit }} caractères minimum"

        prenom:
          - NotBlank: { message : Le prenom est obligatoire }
          - Length:
              min: 3
              max: 30
              maxMessage: "Le prénom ne doit pas dépasser {{ limit }} caractères"
              minMessage: "Le prénom doit contenir {{ limit }} caractères minimum"