renaud\BlogBundle\Entity\ArticleLu:
    type: entity
    table: null
    repositoryClass: renaud\BlogBundle\Repository\ArticleLuRepository
    id:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
    fields:
        lu:
            type: boolean

    lifecycleCallbacks: {  }
    manyToOne:
        article:
            targetEntity: Article
            inversedBy: ArticleLu
            joinColumn:
                name: article
                referencedColumnName: id
        user:
            targetEntity: User
            inversedBy: ArticleLu
            joinColumn:
                name: user
                referencedColumnName: id
                