<?php

namespace renaud\BlogBundle\Repository;

/**
 * ArticleLuRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ArticleLuRepository extends \Doctrine\ORM\EntityRepository
{
}
